language: cpp

git:
  depth: 500

matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode7
    env: SHADOW_BUILD_DIR=/tmp/build_ios

cache:
  directories:
  - $HOME/.ccache

before_install:
- cd ${TRAVIS_BUILD_DIR}
- git fetch --unshallow && git fetch --all --tags

install:
- wget https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.5.1-ios.tar.bz2
- mkdir -p ~/qt-ios
- tar jxf Qt5.5.1-ios.tar.bz2 -C ~/qt-ios
- export PATH=~/qt-ios/ios/bin:$PATH

before_script:
- openssl aes-256-cbc -k "${IOS_PASSWORD}" -in ${TRAVIS_BUILD_DIR}/deploy/iosCerts/QGroundControl_Distribution.mobileprovision.enc -d -a -out ${TRAVIS_BUILD_DIR}/deploy/iosCerts/QGroundControl_Distribution.mobileprovision
- openssl aes-256-cbc -k "${IOS_PASSWORD}" -in ${TRAVIS_BUILD_DIR}/deploy/iosCerts/dist.cer.enc -d -a -out ${TRAVIS_BUILD_DIR}/deploy/iosCerts/dist.cer
- openssl aes-256-cbc -k "${IOS_PASSWORD}" -in ${TRAVIS_BUILD_DIR}/deploy/iosCerts/dist.p12.enc -d -a -out ${TRAVIS_BUILD_DIR}/deploy/iosCerts/dist.p12
- mkdir ${SHADOW_BUILD_DIR}
- cd ${SHADOW_BUILD_DIR}
- qmake -r ${TRAVIS_BUILD_DIR}/qgroundcontrol.pro CONFIG+=WarningsAsErrorsOn CONFIG-=debug_and_release CONFIG+=release

script:
- cd ${SHADOW_BUILD_DIR}
- xcodebuild -configuration Release

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/60b033428ae9dc715662
    on_success: change
    on_failure: always
    on_start: never

env:
  global:
    # IOS_PASSWORD
    - secure: bm0F4DVA3jb4g5Knq6PNqr8hm0pKbAv0oS3h9Y3EMjMSYCXY9kbuWChIM5PElAIx6oGGkf1QDWIQgcZ1kGsEFEFAViL9JBGDUUlnhEiWIefeSZ+CEr98f8h1pwl+RVpTC4hq4ClKhfxS4h14rQJZzc/4vvPdR4nwzjHBC6HFJejygf3tX4WJQOIxFrIcUdiCPpKskrDTiXxuEVj3x3m0m1oQF2u6JSxaQW6F4FhDywCv39URoK/UD7jy24Q4Lg5wqPawcAWn+v8dbLzFtWFHNYqCB1NW36+dZLXMYNQZaTznkfLixtqsRECrYrmv4eIitWsiEL3wov2p70OATpV7nBn8QCjnpWqAMMwU+6OJ2j9oHrPV9XBwSwJ3CQPqOIN+C7h7jUoY4e2+iMB6XnBbarVyfgr+nPZj0RPzMS0bQfo8TBJ8KaTQSRjvLQNoJ9sXyEQ5/F5Kjne4ZhGx57RYctjULdD1xTBcUWWf2Za23zcpprBjU2oTejNEUXxTIqpU4qMTbcBpeSchUJw93EgvuAr9vtpp61GfdJhnxcYCSAj12ewzDyHWrFcq623rFXXvMX2FxdzHOWk3zyh8LiVCgGvy7og61Sma1ffTNahDRMg/+mweG1CNwlkD9Q4gkLprFh0DHac9P8H3PJvMqx1mcAqG884j1mH6pi3qhBDH12Q=
    - APP_NAME="QGroundControl"
    - 'DEVELOPER_NAME="iOS Distribution: Donald Gagne (BDJKVNW2ZQ)"'
    - PROFILE_NAME="QGroundControl_Distribution"
