language: cpp

git:
  depth: 500

matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode7
    env: SHADOW_BUILD_DIR=/tmp/build_ios

cache:
  directories:
  - $HOME/.ccache

before_install:
- cd ${TRAVIS_BUILD_DIR}
- git fetch --unshallow && git fetch --all --tags

install:
- wget https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.5.1-ios.tar.bz2
- mkdir -p ~/qt-ios
- tar jxf Qt5.5.1-ios.tar.bz2 -C ~/qt-ios
- export PATH=~/qt-ios/ios/bin:$PATH

before_script:
- openssl aes-256-cbc -k "${IOS_PASSWORD}" -in ${TRAVIS_BUILD_DIR}/deploy/iosCerts/QGroundControl_Distribution.mobileprovision.enc -d -a -out ${TRAVIS_BUILD_DIR}/deploy/iosCerts/QGroundControl_Distribution.mobileprovision
- openssl aes-256-cbc -k "${IOS_PASSWORD}" -in ${TRAVIS_BUILD_DIR}/deploy/iosCerts/dist.cer.enc -d -a -out ${TRAVIS_BUILD_DIR}/deploy/iosCerts/dist.cer
- openssl aes-256-cbc -k "${IOS_PASSWORD}" -in ${TRAVIS_BUILD_DIR}/deploy/iosCerts/dist.p12.enc -d -a -out ${TRAVIS_BUILD_DIR}/deploy/iosCerts/dist.p12
- mkdir ${SHADOW_BUILD_DIR}
- cd ${SHADOW_BUILD_DIR}
- qmake -r ${TRAVIS_BUILD_DIR}/qgroundcontrol.pro CONFIG+=WarningsAsErrorsOn CONFIG-=debug_and_release CONFIG+=release

script:
- cd ${SHADOW_BUILD_DIR}
- xcodebuild -configuration Release

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/60b033428ae9dc715662
    on_success: change
    on_failure: always
    on_start: never

env:
  global:
    - APP_NAME="QGroundControl"
    - 'DEVELOPER_NAME="iOS Distribution: Donald Gagne (BDJKVNW2ZQ)"'
    - PROFILE_NAME="QGroundControl_Distribution"
