language: cpp

git:
  depth: 500

matrix:
    fast_finish: true
    include:
        - os: osx
            osx_image: xcode7
            env: SPEC=ios CONFIG=release SHADOW_BUILD_DIR=/tmp/build_ios

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ccache
    - doxygen
    - espeak
    - g++-4.8
    - gcc-4.8
    - graphviz
    - libc6-i386
    - libespeak-dev
    - libopenscenegraph-dev
    - libsdl1.2-dev
    - libudev-dev
    - texlive-font-utils

cache:
  directories:
    - $HOME/.ccache


before_install:
    - cd ${TRAVIS_BUILD_DIR} && git fetch --unshallow && git fetch --all --tags
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        mkdir -p ~/.config/QtProject/ &&
        cp ${TRAVIS_BUILD_DIR}/test/qtlogging.ini ~/.config/QtProject/;
    fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        mkdir -p ~/Library/Preferences/QtProject/ &&
        cp ${TRAVIS_BUILD_DIR}/test/qtlogging.ini ~/Library/Preferences/QtProject/;
    fi
    - if [ "${TRAVIS_OS_NAME}" = "android" ]; then
        wget https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/gstreamer-1.0-android-armv7-1.5.2.tar.bz2 &&
        mkdir -p ${TRAVIS_BUILD_DIR}/gstreamer-1.0-android-armv7-1.5.2 &&
        tar jxf gstreamer-1.0-android-armv7-1.5.2.tar.bz2 -C ${TRAVIS_BUILD_DIR}/gstreamer-1.0-android-armv7-1.5.2;
    fi

install:
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
        brew update &&
        brew install qt5 &&
        export PATH=/usr/local/opt/qt5/bin:$PATH;
    fi

before_script:
    # setup ccache
    - mkdir -p ~/bin
    - ln -s /usr/bin/ccache ~/bin/g++
    - ln -s /usr/bin/ccache ~/bin/g++-4.8
    - ln -s /usr/bin/ccache ~/bin/gcc
    - ln -s /usr/bin/ccache ~/bin/gcc-4.8
    - export PATH=~/bin:$PATH
    - if [[ "${TRAVIS_OS_NAME}" = "android" && "${CONFIG}" = "installer" && -z ${ANDROID_STOREPASS} ]]; then
        export CONFIG=release;
    fi
    - if [ "${CONFIG}" != "doxygen" ]; then
        mkdir ${SHADOW_BUILD_DIR} &&
        cd ${SHADOW_BUILD_DIR} &&
        qmake -r ${TRAVIS_BUILD_DIR}/qgroundcontrol.pro CONFIG+=${CONFIG} CONFIG+=WarningsAsErrorsOn -spec ${SPEC};
    fi

script:
    - cd ${TRAVIS_BUILD_DIR} && ./tools/update_android_version.sh
    - echo 'Building QGroundControl' && echo -en 'travis_fold:start:script.1\\r'
    - cd ${SHADOW_BUILD_DIR} && xcodebuild -configuration Release;
    - echo -en 'travis_fold:end:script.1\\r'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/60b033428ae9dc715662
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

