    language: cpp

git:
  depth: 500

env:
  global:
    # ANDROID_STOREPASS
    secure: RGovyUnMw3fp/bHZi058JvANT1rYmNqrsuSYew0cIgirO6YbMHr/rsjwCm1FTYpBl8s1zgr+u2b8ftYnfnCz2YT+Aip4NWrVYpVU0FEmfytGILrnUS0pjlt8m7fU9AKR1ElOSll7yw7e1kftynN39Q321etvwbLZcXon6zz0suE=

matrix:
    fast_finish: true
    include:
        - os: linux
          env: SPEC=linux-g++-64 CONFIG=debug SHADOW_BUILD_DIR=/tmp/build_linux_debug
          sudo: required
          dist: trusty
        - os: linux
          env: SPEC=linux-g++-64 CONFIG=installer SHADOW_BUILD_DIR=/tmp/build_linux_install
          sudo: required 
          dist: trusty
        - os: osx
          osx_image: xcode7
          env: SPEC=macx-clang CONFIG=debug QT_FATAL_WARNINGS=1 SHADOW_BUILD_DIR=/tmp/build_macos_debug
        - os: osx
          osx_image: xcode7
          env: SPEC=macx-clang CONFIG=installer SHADOW_BUILD_DIR=/tmp/build_macos_install
#        - os: android
#          language: android
#          env: SPEC=android-g++ CONFIG=debug SHADOW_BUILD_DIR=/tmp/build_android_debug
#          sudo: false
        - os: android
          language: android
          env: SPEC=android-g++ CONFIG=installer SHADOW_BUILD_DIR=/tmp/build_android_install
          sudo: false
        - os: linux
          env: CONFIG=doxygen
          sudo: false

android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-21

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ccache
    - doxygen
    - espeak
    - g++-4.8
    - gcc-4.8
    - graphviz
    - libc6-i386
    - libespeak-dev
    - libopenscenegraph-dev
    - libsdl1.2-dev
    - libudev-dev
    - texlive-font-utils

cache:
  directories:
    - $HOME/.ccache

before_install:
    - cd ${TRAVIS_BUILD_DIR}
    - ./Travis/before_install.sh

install:
    - cd ${TRAVIS_BUILD_DIR}
    - ./Travis/install.sh

before_script:
    - cd ${TRAVIS_BUILD_DIR}
   - ./Travis/before_script.sh

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./Travis/script.sh

after_success:
  - if [ "${TRAVIS_TAG}" ]; then export GOOGLE_PLAY_TRACK=production; else export GOOGLE_PLAY_TRACK=beta; fi
  - if [[ "${TRAVIS_OS_NAME}" = "android" && "${TRAVIS_PULL_REQUEST}" = "false" && "${TRAVIS_BRANCH}" = "master" ]]; then
         pip install --user google-api-python-client PyOpenSSL
      && cd ${TRAVIS_BUILD_DIR} && openssl aes-256-cbc -K $encrypted_25db6eb7c3fd_key -iv $encrypted_25db6eb7c3fd_iv -in ${TRAVIS_BUILD_DIR}/android/Google_Play_Android_Developer-4432a3c4f5d1.json.enc -out android/Google_Play_Android_Developer-4432a3c4f5d1.json -d
      && ${TRAVIS_BUILD_DIR}/tools/google_play_upload.py ${GOOGLE_PLAY_TRACK} org.mavlink.qgroundcontrol ${SHADOW_BUILD_DIR}/release/package/qgroundcontrol.apk
      ;
    fi

before_deploy:
  - rvm 1.9.3 do gem install mime-types -v 2.6.2

deploy:
  - provider: s3
    access_key_id: AKIAIVORNALE7NHD3T6Q
    secret_access_key:
      secure: BsLXeXUPsCJdX4tawrDnO8OFK5Hk4kzlDTiyH93En6TbjUargVAWDMcHVj7TUhr7+3Tao1W1zb0G4SJe9kHv+jrky0yE72KvoG3YAON0VXWKizxBAKkgHE2RxSTNAwDeKbi2G6YJfNDescBBfX7zEohShdXglQu7CGaUQKRaiI4=
    bucket: qgroundcontrol
    local_dir: ${SHADOW_BUILD_DIR}/release/package
    upload-dir: ${TRAVIS_BRANCH}
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    on:
      all_branches: true
      condition: $CONFIG = installer
  - provider: releases
    api-key:
      secure: K/Zqr/FCC7QvzFxYvBtCinPkacQq2ubJ2qm982+38Zf/KjibVOF1dEbVdrGZmII6Tg5DaQzNXGYkg5PvYmJgT9xRsqeQjeYIUYqYZpAt+HYWA38AVfMU8jip/1P1wmwqD469nzJOBBa8yfsMs6Ca7tBaNl/zTxCRGnAgEzqtkdQ=
    file_glob: true
    file:
      - ${SHADOW_BUILD_DIR}/release/package/qgroundcontrol.*
    skip_cleanup: true
    on:
      tags: true
      condition: $CONFIG = installer
  - provider: s3
    access_key_id: AKIAIVORNALE7NHD3T6Q
    secret_access_key:
      secure: BsLXeXUPsCJdX4tawrDnO8OFK5Hk4kzlDTiyH93En6TbjUargVAWDMcHVj7TUhr7+3Tao1W1zb0G4SJe9kHv+jrky0yE72KvoG3YAON0VXWKizxBAKkgHE2RxSTNAwDeKbi2G6YJfNDescBBfX7zEohShdXglQu7CGaUQKRaiI4=
    bucket: qgroundcontrol
    local_dir: ${TRAVIS_BUILD_DIR}/src/html
    upload-dir: doxygen
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    branch: master
    on:
      condition: $CONFIG = doxygen

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/60b033428ae9dc715662
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

