name: Upload Release
description: Uploads a built release file
inputs:
  artifact_name:
    description: artifact name
    required: true
  aws_key_id:
    description: aws key id
    required: true
  aws_secret_access_key:
    description: aws secret access key
    required: true
runs:
  using: "composite"
  steps:
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: us-west-2

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}

    - name: Upload build to S3 Bucket
      if: github.event_name == 'push'
      shell: bash
      run: aws s3 cp ${{ inputs.artifact_name }} s3://qgroundcontrol/builds/${{ github.ref_name }}/${{ inputs.artifact_name }} --acl public-read

    - name: Upload tagged stable build to S3 latest Bucket
      if: github.event_name == 'push' && github.ref_type == 'tag'
      shell: bash
      run: aws s3 cp ${{ inputs.artifact_name }} s3://qgroundcontrol/latest/${{ inputs.artifact_name }} --acl public-read
