name: Linux - Compile and run unit tests

on: [pull_request]

defaults:
  run:
    shell: bash

env:
  JOBS: 4
  CONFIG: installer
  ACTIONS_BUILD_DIR: ${{ github.workspace }}/../qgroundcontrol

jobs:
  build-job:
    runs-on: ubuntu-20.04
    env:
      gst_version: "1.18.1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version:      '5.12.6'
          host:         'linux'
          target:       'desktop'
          dir:          '${{ runner.temp }}'
          modules:      'qtcharts'
          setup-python: 'false'

      - name: Install QGC source dependencies
        run: sudo apt-get install -y libsdl2-dev

      - name: Install dependencies for running QGC in image
        run: sudo apt-get install -y libxkbcommon-x11-0

      - name: Build
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run:  |
              export JOBS=$((`sysctl -n hw.ncpu`+1))
              mkdir ${{ runner.temp }}/shadow_build_dir
              qmake -r ${ACTIONS_BUILD_DIR}/qgroundcontrol.pro
              make -j$JOBS

      - name: Unit tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ${{ runner.temp }}/shadow_build_dir  
          run:  |
                mkdir -p ~/.config/QtProject/
                cp ${ACTIONS_BUILD_DIR}/test/qtlogging.ini ~/.config/QtProject/
                export QT_FATAL_WARNINGS=1
                ./staging/qgroundcontrol-start.sh --unittest
