name: Docker build

on:
  push:
    branches:
      - 'master'
      - 'Stable*'
    tags:
      - 'v*'
  pull_request:
    branches:
    - '*'

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build --file ./deploy/docker/Dockerfile-build-linux -t qgc-linux-docker .

      - name: Build QGC
        run: |
              mkdir build 
              docker run --rm -v ${PWD}:/project/source -v ${PWD}/build:/project/build qgc-linux-docker
