name: Linux

on:
  push:
    branches:
      - master
      - 'Stable*'
    tags:
      - 'v*'
    paths-ignore:
      - 'android/**'
      - 'deploy/**'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'android/**'
      - 'deploy/**'
      - 'docs/**'
      - '.github/workflows/docs_deploy.yml'
      - '.github/workflows/android.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'

env:
  ARTIFACT: QGroundControl.AppImage

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        BuildType: [Debug, Release]

    defaults:
      run:
        shell: bash

    outputs:
      build: ${{ steps.upload.outputs.build }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true

      - name: Install Dependencies
        uses: ./.github/actions/dependencies

      - name: Install Qt
        uses: ./.github/actions/qt
        with:
          host: linux
          arch: gcc_64

      - name: Build QGC
        uses: ./.github/actions/qgc
        with:
          build: ${{ matrix.BuildType }}
          artifact: ${{ env.ARTIFACT }}

      - name: Publish?
        id: upload
        run: echo "build=${{ matrix.BuildType }}" >> "$GITHUB_OUTPUT"

  publish:
    if: github.event_name == 'push' && needs.build.outputs.build == 'Release'
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Publish Build File
        if: needs.build.outputs.build
        uses: ./.github/actions/upload
        with:
          artifact_name: ${{ env.ARTIFACT }}
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
